### ISSUE TITLE
The meta.csv file could not be found.

### ISSUE THREAD

**Issue by Yulv-git** [p4rallax/SIIMCOV19-Kaggle-MMDetection#1]
FileNotFoundError: [Errno 2] No such file or directory: 'data/meta.csv'

Excuse me, what is meta.csv?

**Comment by p4rallax** [comment]
Hi , 
I am using this [dataset](https://www.kaggle.com/xhlulu/siim-covid19-resized-to-512px-jpg) , the meta.csv file is a part of it. Please download the dataset and extract it into /data/ in the root working dir.
